### ISSUE TITLE
Message generation with type containers

### ISSUE THREAD

**Issue by jheubuch** [d0972058277/KnstEventBus#3]
When a message type should be a list or array, there is no way to tell.
In the case, I annotate a method with a list or an array (like List<Type> or Type[]) I get an Exception which tells me, that the component field name has to match a regex.

![image](https://user-images.githubusercontent.com/60344409/105159455-63af4500-5b0f-11eb-8841-51a5dc69a828.png)

**Comment by d0972058277** [comment]
Got it, thanks.

**Comment by d0972058277** [comment]
I updated the package version to 1.1.1
But there are restrictions on the use of array.
You must create a class that inherits List.

Like:
```
public class HelloWorlds : List<HelloWorld> { }
```
